const PUSH_LIST = 'PUSH_LIST';
const EDIT_ITEM = 'EDIT_ITEM';
const SET_SERVICE_INPUT = 'SET_SERVICE_INPUT';
const SET_PRICE_INPUT = 'SET_PRICE_INPUT';
const CHANGE_EDIT = 'CHANGE_EDIT'; 
const REMOVE_ITEM = 'REMOVE_ITEM';

export  {
    PUSH_LIST, EDIT_ITEM, SET_SERVICE_INPUT,
     SET_PRICE_INPUT, CHANGE_EDIT,REMOVE_ITEM
}